### ISSUE TITLE
CAIP-122 example doesn't conform to spec

### ISSUE THREAD

**Issue by bumblefudge** [ChainAgnostic/namespaces#66]
As @silverpill pointed out in [another thread](https://github.com/ChainAgnostic/namespaces/issues/41#issuecomment-1500659237), the example in CAIP-122 lists an address in Solana-native format, NOT in CAIP-10 format as [specified above](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-122.md?plain=1#L37) in the spec.  Shouldn't it [line 116](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-122.md?plain=1#L116)
read 
`solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp:GwAF45zjfyGzUbd3i3hXxzGeuchzEZXwpRYHZM5912F1` 
instead of
`GwAF45zjfyGzUbd3i3hXxzGeuchzEZXwpRYHZM5912F1` 
?

@haardikk21 @ukstv @zachferland someone who knows solana help me out here :D

**Comment by haardikk21** [comment]
Good catch, definitely an oversight in the namespace spec.

The point of contention here is that SIWx was inspired by EIP-4361 - which does not require CAIP-10 in the `address` field, but CAIP-122 does.

Does this imply that the EIP-155 namespace spec for CAIP-122 will be divergent from EIP-4361? Or do we remove the CAIP-10 requirement from CAIP-122 entirely?

**Comment by silverpill** [comment]
From the user's perspective, plain address is better, because it looks familiar and usually matches account ID used by wallet. CAIP-10 identifiers are harder to read and understand. I think the most sensible approach is to use plain address when displaying a message, and use CAIP-10 identifiers internally

**Comment by haardikk21** [comment]
> From the user's perspective, plain address is better, because it looks familiar and usually matches account ID used by wallet. CAIP-10 identifiers are harder to read and understand. I think the most sensible approach is to use plain address when displaying a message, and use CAIP-10 identifiers internally

I think the question about how closely we want to tie EIP-155 CAIP-122 spec with EIP-4361 remains. Regardless of whether the address is displayed in the message or not, is a CAIP-10 URN mandated in the data model? 

It matters because when verifying signatures, or validating SIWE objects, or creating CACAO (CAIP-74) objects - the data model values matter because they're not re-parsed from the message representation - unless, of course, all of those specs then include notes to basically slice the URN into only it's address part

**Comment by bumblefudge** [comment]
closed by #236
